# github action 名稱
name: Todo list

# 在哪個 branch 會觸發 github action 動作
on:
 push:
   branches: ["main"]
 pull_request:
   branches: ["main"]

jobs:
 # job
 # test mocha
 test:
   runs-on: "ubuntu-latest"
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          check-latest: true
      - name: Install & Test
        run: |
          npm install -g mocha
          npm install
          npm run test
## test eslint
 lint:
   runs-on: "ubuntu-latest"
   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          check-latest: true
      - name: Install & Test
        run: |
          npm install -g eslint
          npm install
          npm run lint